import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarMenu from "@/components/navbar/Navbar";
import SidebarMenu from "@/components/sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Big Forum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
        {/* <NavbarMenu />
        <SidebarMenu /> */}
        </main>
        {children}
        </body>
    </html>
  );
}
